# Generated by Django 3.0.5 on 2020-08-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=15, verbose_name='商品标题')),
                ('price', models.IntegerField(verbose_name='商品价格')),
                ('intro', tinymce.models.HTMLField(verbose_name='简介')),
                ('place', models.CharField(max_length=20, verbose_name='希望交易地点')),
                ('surface', models.ImageField(upload_to='goods', verbose_name='商品封面')),
                ('classify', models.CharField(max_length=5, verbose_name='所属类别')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('like_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('display_type', models.SmallIntegerField(choices=[(0, '下架'), (1, '在售'), (2, '售出')], default=1, verbose_name='商品状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'utp_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('hash', models.CharField(max_length=128, verbose_name='图片编号')),
                ('image', models.ImageField(upload_to='goods', verbose_name='图片')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'utp_goods_img',
            },
        ),
    ]
