# Generated by Django 3.0.5 on 2020-08-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('trading_place', models.CharField(max_length=20, verbose_name='交易地点')),
                ('head_img', models.ImageField(upload_to='head', verbose_name='头像')),
                ('nickname', models.CharField(max_length=6, verbose_name='昵称')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('QQ', models.CharField(max_length=20, verbose_name='QQ号')),
                ('WeChat', models.CharField(max_length=20, verbose_name='微信号')),
                ('signature', models.CharField(max_length=20, verbose_name='个性签名')),
                ('date_birth', models.CharField(max_length=10, verbose_name='生日')),
                ('college', models.CharField(max_length=20, verbose_name='学院')),
                ('apartment', models.CharField(max_length=5, verbose_name='寝室楼')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'utp_user',
            },
        ),
    ]
