# Generated by Django 3.0.5 on 2020-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200815_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='QQ',
            field=models.CharField(blank=True, max_length=20, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='WeChat',
            field=models.CharField(blank=True, max_length=20, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.CharField(blank=True, max_length=5, verbose_name='寝室楼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.CharField(blank=True, max_length=10, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.ImageField(blank=True, upload_to='head', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=6, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=20, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trading_place',
            field=models.CharField(blank=True, max_length=20, verbose_name='交易地点'),
        ),
    ]
