# Generated by Django 3.0.5 on 2020-08-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('hash', models.CharField(max_length=128, verbose_name='订单编号')),
                ('price', models.IntegerField(verbose_name='成交价格')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('pay_method', models.SmallIntegerField(choices=[(3, '支付宝'), (1, '当面付款'), (2, '微信支付')], default=1, verbose_name='支付方式')),
                ('order_status', models.SmallIntegerField(choices=[(4, '已完成'), (2, '待交易'), (3, '待评价'), (1, '待付款')], default=2, verbose_name='订单状态')),
                ('trade_no', models.CharField(max_length=128, verbose_name='支付编号')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='所属商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属账号')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
                'db_table': 'utp_order',
            },
        ),
    ]
