# Generated by Django 3.0.5 on 2020-08-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200822_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(4, '已完成'), (3, '待评价'), (1, '待付款'), (2, '待交易')], default=2, verbose_name='订单状态'),
        ),
    ]
