# Generated by Django 3.0.5 on 2020-08-21 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200822_0710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_auto_20200822_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='goods.Goods', verbose_name='所属商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(2, '待交易'), (1, '待付款'), (3, '待评价'), (4, '已完成')], default=2, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(3, '支付宝'), (2, '微信支付'), (1, '当面付款')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL, verbose_name='所属账号'),
        ),
    ]
